name: my-workflow
on:
  pull_request:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: bun --filter "*" typecheck
      - run: bun --filter "*" lint
      - run: bun --filter "*" test --coverage
